from pathlib import Path

root = Path('/home/ubuntu/catfish_farm_logger')
finance = root / 'app/(tabs)/finance.tsx'
text = finance.read_text()
text = text.replace('import { calculateEconomicsSummary, formatCurrency, formatNumber } from "@/lib/economics";', 'import { assessFeedEfficiencyProfitRisk, calculateEconomicsSummary, formatCurrency, formatNumber } from "@/lib/economics";')
text = text.replace('  const summary = useMemo(() => calculateEconomicsSummary(scopedCosts, scopedSales), [scopedCosts, scopedSales]);\n', '  const scopedFeedings = useMemo(() => farm.feedings.filter((item) => !selectedTankId || item.tankId === selectedTankId), [farm.feedings, selectedTankId]);\n  const scopedGrowthMeasurements = useMemo(() => farm.growthMeasurements.filter((item) => !selectedTankId || item.tankId === selectedTankId), [farm.growthMeasurements, selectedTankId]);\n  const summary = useMemo(() => calculateEconomicsSummary(scopedCosts, scopedSales), [scopedCosts, scopedSales]);\n  const managementAlert = useMemo(() => assessFeedEfficiencyProfitRisk({ costs: scopedCosts, sales: scopedSales, feedings: scopedFeedings, growthMeasurements: scopedGrowthMeasurements }), [scopedCosts, scopedSales, scopedFeedings, scopedGrowthMeasurements]);\n')
insert_after = '''            <View className="mt-4 flex-row flex-wrap gap-3">\n              <Metric label="Total cost" value={formatCurrency(summary.totalCost)} tone="warning" />\n              <Metric label="Sales" value={formatCurrency(summary.totalSales)} tone="success" />\n              <Metric label="Gross profit" value={formatCurrency(summary.grossProfit)} tone={summary.grossProfit >= 0 ? "success" : "error"} />\n              <Metric label="Cost / kg sold" value={summary.costPerKgSold === null ? "未計算" : formatCurrency(summary.costPerKgSold)} tone="muted" />\n            </View>\n'''
alert_card = '''            <View className="mt-4 rounded-3xl border border-border bg-surface p-5">\n              <View className="flex-row items-start justify-between gap-3">\n                <View className="flex-1">\n                  <Text className="text-xl font-bold text-foreground">FCR・利益率アラート</Text>\n                  <Text className="mt-1 text-sm leading-5 text-muted">給餌量、平均体重の増加、販売収支を組み合わせ、飼料効率と採算の悪化を早めに確認します。</Text>\n                </View>\n                <View className={`rounded-full px-3 py-1 ${severityBadgeClass(managementAlert.severity)}`}>\n                  <Text className="text-xs font-extrabold text-white">{severityLabel(managementAlert.severity)}</Text>\n                </View>\n              </View>\n              <Text className="mt-4 text-base font-bold text-foreground">{managementAlert.title}</Text>\n              <Text className="mt-2 text-sm leading-5 text-muted">{managementAlert.summary}</Text>\n              <View className="mt-4 flex-row flex-wrap gap-2">\n                <MiniMetric label="推定FCR" value={managementAlert.fcr === null ? "未計算" : formatNumber(managementAlert.fcr, 2)} />\n                <MiniMetric label="増加バイオマス" value={managementAlert.biomassGainKg === null ? "未計算" : `${formatNumber(managementAlert.biomassGainKg, 2)} kg`} />\n                <MiniMetric label="利益率" value={managementAlert.marginPercent === null ? "未計算" : `${formatNumber(managementAlert.marginPercent, 1)}%`} />\n                <MiniMetric label="餌代比率" value={managementAlert.feedCostSharePercent === null ? "未計算" : `${formatNumber(managementAlert.feedCostSharePercent, 1)}%`} />\n              </View>\n              {managementAlert.alerts.slice(0, 3).map((alert) => (\n                <View key={alert.id} className="mt-3 rounded-2xl bg-background p-4">\n                  <Text className={`text-sm font-extrabold ${alert.severity === "danger" ? "text-error" : alert.severity === "watch" ? "text-warning" : "text-success"}`}>{alert.title}</Text>\n                  <Text className="mt-1 text-sm leading-5 text-muted">{alert.reason}</Text>\n                  <Text className="mt-2 text-sm leading-5 text-foreground">対応: {alert.action}</Text>\n                </View>\n              ))}\n              <Text className="mt-3 text-xs leading-5 text-muted">{managementAlert.limitation}</Text>\n            </View>\n'''
if alert_card not in text:
    text = text.replace(insert_after, insert_after + '\n' + alert_card)
text += '' if 'function severityBadgeClass' in text else '''\nfunction severityBadgeClass(value: "normal" | "watch" | "danger") {\n  if (value === "danger") return "bg-error";\n  if (value === "watch") return "bg-warning";\n  return "bg-success";\n}\n\nfunction severityLabel(value: "normal" | "watch" | "danger") {\n  if (value === "danger") return "危険";\n  if (value === "watch") return "注意";\n  return "安定";\n}\n\nfunction MiniMetric({ label, value }: { label: string; value: string }) {\n  return (\n    <View className="min-w-[47%] flex-1 rounded-2xl bg-background p-3">\n      <Text className="text-xs font-bold text-muted">{label}</Text>\n      <Text className="mt-1 text-base font-extrabold text-foreground">{value}</Text>\n    </View>\n  );\n}\n'''
finance.write_text(text)

farm_store = root / 'lib/farm-store.tsx'
text = farm_store.read_text()
text = text.replace('import AsyncStorage from "@react-native-async-storage/async-storage";\n', 'import AsyncStorage from "@react-native-async-storage/async-storage";\nimport { assessFeedEfficiencyProfitRisk } from "@/lib/economics";\n') if 'assessFeedEfficiencyProfitRisk' not in text.split('\n', 5)[0:5] else text
text = text.replace('    files: string[];\n  }>;\n};', '    managementAlert: ReturnType<typeof assessFeedEfficiencyProfitRisk>;\n    files: string[];\n  }>;\n};')
text = text.replace('          return {\n          folder: `${state.settings.driveRootFolder}/${safeName}`,', '          const tankCosts = state.costEntries.filter((item) => item.tankId === tank.id);\n          const tankSales = state.saleRecords.filter((item) => item.tankId === tank.id);\n          const tankFeedings = state.feedings.filter((item) => item.tankId === tank.id);\n          const tankGrowthMeasurements = state.growthMeasurements.filter((item) => item.tankId === tank.id);\n          return {\n          folder: `${state.settings.driveRootFolder}/${safeName}`,')
text = text.replace('          feedings: state.feedings.filter((item) => item.tankId === tank.id),', '          feedings: tankFeedings,')
text = text.replace('          growthMeasurements: state.growthMeasurements.filter((item) => item.tankId === tank.id),', '          growthMeasurements: tankGrowthMeasurements,')
text = text.replace('          costEntries: state.costEntries.filter((item) => item.tankId === tank.id),', '          costEntries: tankCosts,')
text = text.replace('          saleRecords: state.saleRecords.filter((item) => item.tankId === tank.id),', '          saleRecords: tankSales,')
text = text.replace('          files: ["tank.json", "inspections.json", "feedings.json", "photos/", "growth-measurements.json", "photo-assessments.json", "costs.json", "sales.json", "economics-summary.json", "growth-status.json", "sync-log.json", "feeding-advice.json"],', '          managementAlert: assessFeedEfficiencyProfitRisk({ costs: tankCosts, sales: tankSales, feedings: tankFeedings, growthMeasurements: tankGrowthMeasurements }),\n          files: ["tank.json", "inspections.json", "feedings.json", "photos/", "growth-measurements.json", "photo-assessments.json", "costs.json", "sales.json", "economics-summary.json", "management-alert.json", "growth-status.json", "sync-log.json", "feeding-advice.json"],')
farm_store.write_text(text)

gdrive = root / 'lib/google-drive.ts'
text = gdrive.read_text()
text = text.replace('{ name: "economics-summary.json", value: { costCount: tankExport.costEntries.length, saleCount: tankExport.saleRecords.length } },', '{ name: "economics-summary.json", value: { costCount: tankExport.costEntries.length, saleCount: tankExport.saleRecords.length } },\n      { name: "management-alert.json", value: tankExport.managementAlert },')
gdrive.write_text(text)

test_path = root / 'tests/app-basic.test.ts'
text = test_path.read_text()
text = text.replace('calculateEconomicsSummary', 'assessFeedEfficiencyProfitRisk, calculateEconomicsSummary') if 'assessFeedEfficiencyProfitRisk' not in text else text
if 'flags combined FCR and margin risk' not in text:
    insertion = '''\n  it("flags combined FCR and margin risk", () => {\n    const alert = assessFeedEfficiencyProfitRisk({\n      costs: [{ id: "c1", category: "feed", label: "feed", amount: 9000, createdAt: "2026-01-01T00:00:00.000Z", tankId: "t1", notes: "", synced: false }],\n      sales: [{ id: "s1", buyer: "buyer", productGrade: "regular", quantityKg: 20, unitPrice: 400, totalAmount: 8000, createdAt: "2026-01-20T00:00:00.000Z", tankId: "t1", notes: "", synced: false }],\n      feedings: [{ id: "f1", tankId: "t1", createdAt: "2026-01-10T00:00:00.000Z", feedType: "pellet", feedAmountKg: 30, averageWeightG: 100, fishCount: 100, notes: "", synced: false }],\n      growthMeasurements: [\n        { id: "g1", tankId: "t1", createdAt: "2026-01-01T00:00:00.000Z", lengthCm: 12, weightG: 100, source: "manual", notes: "", synced: false },\n        { id: "g2", tankId: "t1", createdAt: "2026-01-20T00:00:00.000Z", lengthCm: 18, weightG: 200, source: "manual", notes: "", synced: false },\n      ],\n    });\n\n    expect(alert.severity).toBe("danger");\n    expect(alert.fcr).toBe(3);\n    expect(alert.marginPercent).toBeLessThan(0);\n    expect(alert.alerts.some((item) => item.id === "combined_feed_profit_danger")).toBe(true);\n  });\n'''
    text = text.replace('\n});\n', insertion + '\n});\n')
test_path.write_text(text)
